server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_parking_system
    username: root
    password: root
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp
   
