server:
  port: 8090
spring:
  datasource: 
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_application
    username: root
    password: root
  mvc:
   view:
    prefix: /WEB-INF/pages/
    suffix: .jsp
hibernate: 
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
entitymanager.packagesToScan: com.metacube
